### ISSUE TITLE
Unable to run `go get -u` for projects created with `nx-go` in the workspace

### ISSUE THREAD

**Issue by mhornbacher** [nx-go/nx-go#127]
### Current Behavior

When using `@nx-go/nx-go` to create a library (called flamingo here because its fun) when running go get -u ./... from within the `go.work` workspace it crashes as it looks for it in the std library and not the workspace.

Command used on the latest version: (the code is not changed)
```
npx nx generate @nx-go/nx-go:library \
  --name=test \
  --directory=libraries/test \
  --projectNameAndRootFormat=as-provided
```

Usage in `main.go`:
```
package main

import (
	_ "apps/api/docs"
	"apps/api/routes"
	"libraries/test"

	"github.com/labstack/echo/v4"
)

func newServer() *echo.Echo {
        // import from the other pacakge
	_ = test.Test("works")

	e.GET("/", routes.Home)
	return e
}

func main() {
	e := newServer()
	e.Logger.Fatal(e.Start(":8080"))
}
```

Current Output:
```
go: apps/api imports
        libraries/test: package libraries/test is not in std (/nix/store/460vdyz0ghxh8n5ibq3fgc3s63is68cd-go-1.22.2/share/go/src/libraries/test)
```

### Expected Behavior

The dependency should resolve when imported and running `go get -u ./...` as it would when created manually under a `github.com/` package name.

### Github Repo

https://github.com/nx-go/nx-go-playground

### Steps to Reproduce

1. Clone the repository
3. Ensure that go 1.22 is installed (tested with both Nix and Homebrew)
4. Run `cd apps/api` to go to the API folder
5. Run `go get -u ./...`

go: nx-go-playground/api imports
        nx-go-playground/logger: package nx-go-playground/logger is not in std (/opt/homebrew/Cellar/go/1.22.5/libexec/src/nx-go-playground/logger)
go: nx-go-playground/api imports
        nx-go-playground/math: package nx-go-playground/math is not in std (/opt/homebrew/Cellar/go/1.22.5/libexec/src/nx-go-playground/math)

### Nx Report

```shell
/bin/sh: pnpm: command not found
nx report

Reports useful version numbers to copy into the Nx issue template

Options:
  --help     Show help                                                                                                        [boolean]
  --version  Show version number                                                                                              [boolean]

Error: Command failed: pnpm --version
/bin/sh: pnpm: command not found

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at getPackageManagerVersion (/Users/menachem/dev/tmp/nx-go-import-bug/node_modules/nx/src/utils/package-manager.js:127:41)
    at getReportData (/Users/menachem/dev/tmp/nx-go-import-bug/node_modules/nx/src/command-line/report/report.js:95:70)
    at Object.reportHandler (/Users/menachem/dev/tmp/nx-go-import-bug/node_modules/nx/src/command-line/report/report.js:39:159)
    at Object.handler (/Users/menachem/dev/tmp/nx-go-import-bug/node_modules/nx/src/command-line/report/command-object.js:8:73) {
  status: 127,
  signal: null,
  output: [ null, '', '/bin/sh: pnpm: command not found\n' ],
  pid: 34782,
  stdout: '',
  stderr: '/bin/sh: pnpm: command not found\n'
}
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "affected": {
    "defaultBase": "main"
  },
  "namedInputs": {
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals"
    ],
    "production": [
      "default"
    ],
    "sharedGlobals": [
      "{workspaceRoot}/go.work"
    ]
  },
  "plugins": [
    "@nx-go/nx-go"
  ]
}
```

### Failure Logs

```shell
go: nx-go-playground/api imports
        nx-go-playground/logger: package nx-go-playground/logger is not in std (/opt/homebrew/Cellar/go/1.22.5/libexec/src/nx-go-playground/logger)
go: nx-go-playground/api imports
        nx-go-playground/math: package nx-go-playground/math is not in std (/opt/homebrew/Cellar/go/1.22.5/libexec/src/nx-go-playground/math)
```

### Go Version

go version go1.22.5 darwin/arm64

**Comment by mhornbacher** [comment]
Small update, at the moment I found a workaround by adding a `replace` to the `go.mod`. While this works it has the negative side effect of importing all the libraries dependencies as well which causes a headace for auditing dependencies :(

```
go mod edit -replace libraries/flamingo=../../libraries/flamingo
```

**Comment by utarwyn** [comment]
Hello @mhornbacher,  thanks for the detailed feedback on this "bug"!
I managed to reproduce it on the playground too, it's embarrassing.

Unfortunately, it seems to be related to the way Golang workspaces work (see https://github.com/golang/go/issues/50750). The simplest solution is to have a module file at the root of the project with all the workspace dependencies, or not to use a workspace at all. I recognize that this conclusion is not acceptable. I think this is beyond my scope... 😢 unless you have a great idea

**Comment by mhornbacher** [comment]
Hey @utarwyn you are very welcome! Your tool is truly amazing, and a clear report is really the least I can do.

It being an issue with go and not the tool is, at least in my not-so-humble opinion, a conclusion that is more than acceptable.

For myself, we have introduced some notes to the internal documentation on the repository to tell service creators to remember to add replace directives after creating a repo.

Maybe we can automatically insert them based on the NX graph. But honestly, given that this is an ongoing discussion in the go ecosystem, I would shy away from making such a change until the discussion is finalized.

Thank you so so much for taking a look at this and I am sorry for apparently wasting your time.

Would you like me to open a PR against the playground to fix this issue with a `replace` call and to add to the documentation there that it is something that must be manually added?

**Comment by mhornbacher** [comment]
@utarwyn are you against me writing the details of this up in the ideas section of the Discussions tab and closing this issue?

This will allow future engineers running into this issue to find a resolution quickly, as well as provide a point to reference without clogging up the Issues tab :)

**Comment by utarwyn** [comment]
@mhornbacher Sorry for the reply delay, I've been busy the last few days.

I agree with your conclusion that this is a concern for the Go ecosystem.

As for nx-go, what you propose is a very good idea: I agree with adapting the playground with the `replace` keyword and documenting this behavior somewhere on the repository. Go for it! Thanks again for the time you've spent finding out all about it.

**Comment by mhornbacher** [comment]
@utarwyn you don't need to apologize. This is a labor of love, and every minute is very much appreciated! I hope the busyness was due to good things!

I'll open a PR for the playground soon to be reviewed at yours or anyone else's convenience.

**Comment by mhornbacher** [comment]
Added a guide to the discussions under at https://github.com/nx-go/nx-go/discussions/129
