### ISSUE TITLE
Working with "affected:" ?

### ISSUE THREAD

**Issue by iangregsondev** [nx-go/nx-go#14]
Hi,

I found this by mistake :-) It is exactly what I wanted though.

I was wondering if it supports (and how) using the affected: scripts i.e.

affected:apps
affected:tests

And what about the dependency graph - is this also supported ?

I suppose I am asking if there is anything that doesn't kind of work because we are using GO inside of a javascript/framework (NX) 

Thanks in advance

**Comment by martonkaufmann** [comment]
I would also like to know how to use the affected:* commands. Are they even available?

**Comment by martonkaufmann** [comment]
> I would also like to know how to use the affected:* commands. Are they even available?

OK, so for anyone else wondering the solution I went with was for defining the dependencies between Go packages was
to add them as implicit dependencies in the nx.json.

nx.json:
```
  "projects": {
    "child1": {
      "tags": []
    },
    "child2": {
      "tags": []
    },
    "parent": {
      "tags": [],
      "implicitDependencies": ["child1", "child2"]
    }
  }
```
These are also defined in the workspace.json under projects:
```
  "projects": {
    "parent": {
      "projectType": "application",
      "root": "services/parent",
      "sourceRoot": "services/parent"
    },
    "child1": {
      "projectType": "application",
      "root": "services/child1",
      "sourceRoot": "services/child1"
    },
    "child2": {
      "projectType": "application",
      "root": "services/child2",
      "sourceRoot": "services/child2"
    }
```

**Comment by beeman** [comment]
At this moment the way to go is by using `implicitDependencies` as suggested by @martonkaufmann

```json
  "projects": {
    "api": {
      "tags": [],
      "implicitDependencies": ["api-db"]
    },
    "api-db": {
      "tags": []
    }
  }
```

I hope in the future this will work as other projects, but I need to dive in how that works.

**Comment by phillipCouto** [comment]
@beeman would you like help with this enhancement?

**Comment by beeman** [comment]
@phillipCouto yes! That would be very welcome 👍

Happy to talk about any issues or questions you might have when working on this - if you happen to be on Discord, I'm `beeman#8333`. Otherwise happy to slow-chat here

**Comment by phillipCouto** [comment]
> @phillipCouto yes! That would be very welcome +1
> 
> Happy to talk about any issues or questions you might have when working on this - if you happen to be on Discord, I'm `beeman#8333`. Otherwise happy to slow-chat here

So far I have gotten it to work using the sample. There are some things I need to tweak to have it work correctly for all workspaces. Would you like the plugin to be a separate package or included in `@nx-go/nx-go` ? I need to test the later as I got it to work as a separate package.

I will setup discord tomorrow =)

**Comment by phillipCouto** [comment]
@beeman check out my branch to see if you are happy with the direction I am going in. If so I will finish it off with unit tests to validate the functionality.

https://github.com/phillipCouto/nx-go/tree/add-package-graph-support

Also I added you to discord I am Speedz#1203.
