### ISSUE TITLE
Project failing to build in docker

### ISSUE THREAD

**Issue by codephobia** [nx-go/nx-go#20]
I created a new empty nx repo, and added the nx-go project from the cli `nx g @nx-go/nx-go:app api`. Then using the example Dockerfile in the readme to build, I get the following error:

`RUN nx build api`

```
can't load package: package appsapisrcmain.go: cannot find module providing package appsapisrcmain.go
Failed to execute command: go build -o dist\apps\api apps\api\src\main.go
```

So I tried changing the run command to the following just to test, and I get a different error but it completes.

`RUN go build -o /workspace/dist/apps/api ./apps/api/src/`

```
# github.com/username/repo-name/apps/api/src
loadinternal: cannot find runtime/cgo
```

Also tried adding a `RUN go mod download` just in case.

Including the Dockerfile as I did make a few slight changes (mostly removing yarn references).

```
# Use nxgo/cli as the base image to do the build
FROM nxgo/cli as builder

# Create app directory
WORKDIR /workspace

# Copy package.json and the lock file
COPY package.json package-lock.json /workspace/

# Install app dependencies
RUN npm i

# Copy source files
COPY . .

# Download go modules
RUN go mod download

# Build apps
RUN nx build api

# This is the stage where the final production image is built
FROM golang:1.14-alpine as final

# Copy over artifacts from builder image
COPY --from=builder /workspace/dist/apps/api /workspace/api

# Set environment variables
ENV PORT=3000
ENV HOST=0.0.0.0

# Expose default port
EXPOSE 3000

# Start server
CMD [ "/workspace/api" ]
```

I did also initialize go mod and added a dockerignore file for node_modules but not sure if that should have any impact on this working.

**Comment by beeman** [comment]
Hey @codephobia - I think we managed to get this running right?

**Comment by codephobia** [comment]
> Hey @codephobia - I think we managed to get this running right?

I honestly think it came down to forgetting to gitignore the dist folder. So my docker image was copying my windows build and then trying to build over it. Such a weird error for such a silly oversight.
