### ISSUE TITLE
nx-go and go modules

### ISSUE THREAD

**Issue by Narven** [nx-go/nx-go#22]
Is is possible to point me to a repo where nx-go and go modules are being used together?

Where are we supose to have the `go.mod` and `go.sum` files? on the root of the project or on inside the apps/go-project?

**Comment by beeman** [comment]
@Narven thanks for your issue and checking out nx-go. I don't have an example that's open source, but in the project I am using nx-go, I have a top-level go.mod, and it works as expected.

So in terms of this project, currently it doesn't have an opinion. 

I will create an update of this project and with that I might make it more opinionated.

**Comment by Narven** [comment]
Thanks for the response. Yes, I finally managed make it work by just putting `go.mod` and `go.sum` in the root older.
Does not feel like the best approach, but its working now.

I think it would be good add some kind of tree structure of the folders/files to give a better understanding. Even if is just a image from an existing project.

**Comment by beeman** [comment]
Hey @Narven , in version 1.6.0 the app that gets generated will put a `go.mod` in the project root if it does not exist.

This seems (to my knowledge) the easiest way to be able to import between the various projects in the workspace:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/36491/107347069-6dcfbe00-6a93-11eb-90e5-715a791609a7.png">

I will update the [nx-go-playground](https://github.com/nx-go/nx-go-playground) with an example.

**Comment by Anthony-Jhoiro** [comment]
Hi @beeman ,
I'm starting to get interested in Nx and I don't understand why you generate the `go.mod` file in the root directory. It might works fine but `go.mod` files are made for only one module as described in the [Go documentation](https://go.dev/doc/modules/managing-source#multiple-module-source). 

Also, I saw that the file is added as an implicitDependency for all projects including non-go projects. That behavior breaks the nx dependency logic. Is it really necessary?
