### ISSUE TITLE
Dockerfile 

### ISSUE THREAD

**Issue by xmlking** [nx-go/nx-go#37]
I have to add `COPY decorate-angular-cli.js .` before `RUN yarn` to make it work. 
not sure if everyone had my issue!

https://github.com/xmlking/yeti/blob/develop/Dockerfile#L11

**Comment by muuvmuuv** [comment]
This is as expected because you are using `ng` instead of `nx` with the `build` command. NX requires the "decorate script" to map their logic into the NG command. In our case, I just removed that script entirely and replace all `ng ..` commands with `nx ...`.
