### ISSUE TITLE
Outdated Nx dependencies 

### ISSUE THREAD

**Issue by wSedlacek** [nx-go/nx-go#46]
https://github.com/nx-go/nx-go/blob/6bc6a4e9ea3a5cf60e0cfb183aceb86967a32707/package.json#L30

Looks like this project is still using v10 for the nx dependencies.
Maybe it would be worth considering using a `peerDependency` and loosening up the versioning to reduce the required maintenance on this library?

**Comment by BalazsSevecsek** [comment]
This is actually a breaking bug in the current implementation.

**Comment by beeman** [comment]
I just released [@nx-go/nx-go v2.0.0](https://www.npmjs.com/package/@nx-go/nx-go/v/2.0.0) which should fix these issues. 

Please give it a try and if it doesn't fix it please provide a reproduction.
