### ISSUE TITLE
Add ability to configure additional linters

### ISSUE THREAD

**Issue by phillipCouto** [nx-go/nx-go#49]
Would be great if we can configure nx-go to use additional linters like:

- vet
- revive
- golangci-lint

The initial release doesn't need to support all or many. It can be the implementation of one and then additional is added from there. Personally for our projects we use vet and revive but more than happy to contribute to implement this feature or add additional linters after the initial feature implementation.

**Comment by beeman** [comment]
@phillipCouto great suggestion - happy to look at supporting this.

Do you think it's similar to how the current implementation supports `gow`?

**Comment by phillipCouto** [comment]
That can be a way to support it initially but unlike how eslint is supported with Nx anyone checking out a workspace using a linter outside of what is shipped with go will require to install the dependencies.I am wondering if we can auto install the linter so that way in CI or when a new team member checks out the project and starts working with it the configured linter will just work without setup steps needing to be defined.

Let me know if this seems to ambitious.

**Comment by beeman** [comment]
I think it's probably good to do it in 2 steps. So first add the ability to define a custom linter command, and later fix the issue of the dependencies.

**Comment by Azuka** [comment]
In addition to this, it would also be nice to add support for a custom test command, e.g. using https://github.com/gotestyourself/gotestsum to output junit files

**Comment by phillipCouto** [comment]
So implementing the similar options as the serve executor for lint and test executors seems like a good starting point. 

Then we can add additional executors if we want improved developer experience or improve the options for the generators to guide the user to configure a project with specific linters or test utilities.

**Comment by beeman** [comment]
This has been released as `@nx-go/nx-go@2.6.0` 🚀
