### ISSUE TITLE
Add go.mod to implicitDependencies in nx.json for proper affected calculations

### ISSUE THREAD

**Issue by phillipCouto** [nx-go/nx-go#52]
We should add `go.mod` to the `implicitDependencies` property in `nx.json` so that when a workspace upgrades or changes go dependencies it properly invalidates all projects forcing them to be included in affected commands.

This is similar as how `package.json`  is in the `implicitDependencies` properties.

**Comment by beeman** [comment]
Great suggestion @phillipCouto - as always I welcome a PR!
