### ISSUE TITLE
Failure to start when using the nx console

### ISSUE THREAD

**Issue by ahahn95** [nx-go/nx-go#63]
Hi, when I run with the following command

```
nx run api:serve
```

I get the following error.

```
Executing command: go run main.go
/bin/sh: go: command not found
Failed to execute command: go run main.go Error: Command failed: go run main.go
```

**Comment by beeman** [comment]
> Hi, when I run with the following command
> 
> ```
> nx run api:serve
> ```
> 
> I get the following error.
> 
> ```
> Executing command: go run main.go
> /bin/sh: go: command not found
> Failed to execute command: go run main.go Error: Command failed: go run main.go
> ```

Do you have Go installed on your machine and available in your path?

**Comment by ahahn95** [comment]
I had it installed as root or something, reinstalling with homebrew seemed to fix this issue. Thanks @beeman
