### ISSUE TITLE
Support Go 1.18 workspaces

### ISSUE THREAD

**Issue by Anthony-Jhoiro** [nx-go/nx-go#73]
# NX-GO : Support Go 1.18 workspaces
Go 1.18 introduces Go workspaces, a clean and nice way to manage a repository that contains multiple modules written in go. It works by adding a `go.wok` file in the root directory and add a `go.mod` file in each go module.

To adapt this solution to nx-go, we need to be able to manage versions before 1.18 (without the `go.work` files) and the next versions.

It can be also nice to add an utility to upgrade the current workspaces to th new module management system.

## App & libs creation
When creating apps and libs we have now 4 use cases. (The first match skip the followings)
- A `go.mod` file is in the root directory: the new package is created as before. 
- A `go.work` file is in the root directory: the package is created with its own `go.mod` file in its directory and it is added in the `use` list in the `go.work` file.
- The option "useWorkspace" is added in the command line the go version is checked, if it is before 1.18 an error is thrown otherwise, a `go.work` file is added in the root directory.
- Same behavior as before 1.18

**Comment by phillipCouto** [comment]
Conceptually looks good, how do we generate the module import path when in a workspace?

Do we treat it similar to the npmScope for javascript / typescript projects?

**Comment by Anthony-Jhoiro** [comment]
Hello @phillipCouto !

Thank you for your answer. I had the same question, I'm just getting started with nx, and I am not sure if adding a `goScope` property in the `nx.json` is a good practice. The behavior could be : 

If the property is set, then the module import path will be the concatenation of the `goScope` property and the module relative path. Otherwise, the module import path will be the relative path of the module.

What do you think about this?

**Comment by system32uwu** [comment]
Hi! Could you be so kind to explain how to get go workspaces working with nx?

From my understading, I should just initialize the workspace in the root directory of the nx project, is this correct?

**Comment by phillipCouto** [comment]
> Hello @phillipCouto !
> 
> Thank you for your answer. I had the same question, I'm just getting started with nx, and I am not sure if adding a `goScope` property in the `nx.json` is a good practice. The behavior could be :
> 
> If the property is set, then the module import path will be the concatenation of the `goScope` property and the module relative path. Otherwise, the module import path will be the relative path of the module.
> 
> What do you think about this?

Sounds good to me! Really sorry for the late reply. I need to review my Github notification settings!

**Comment by phillipCouto** [comment]
> Hi! Could you be so kind to explain how to get go workspaces working with nx?
> 
> From my understading, I should just initialize the workspace in the root directory of the nx project, is this correct?

The current stable version does not yet support it out of the box. As this issue is adding the functionality in question. There is a release candidates for 2.7.0 with support for workspaces though which you can evaluate.

@Anthony-Jhoiro may be better to answer how to use workspaces with 2.7.0 as I have been MIA for a few months and just getting caught up again.
