### ISSUE TITLE
Allow setting build env variables such as GOOS=windows GOARCH=amd64

### ISSUE THREAD

**Issue by the0rem** [nx-go/nx-go#75]
We have a windows-specific app that needs to be built from both our local machines (MacOS) as well as our CI (Linux). We can set environment variable in CI however local development is hindered with this limitation and doesn't really fall within the NX approach if you have to set variables outside of the build tooling.

One suggestion is to pass the `cwd` option to the `runGoCommand` when building. This would allow you to set any environmental variables required.

I'm not sure how you cater for this in `https://github.com/nx-go/nx-go/blob/main/packages/nx-go/src/executors/build/executor.ts` as the file naming logic is looking at the platform to decide whether to set the file extension.

**Comment by johnmckenna** [comment]
@the0rem I think you can set Nx environment variables in files and before the command, does this link help at all? https://nx.dev/recipes/tips-n-tricks/define-environment-variables

**Comment by abramsimon** [comment]
This issue is stale and should be closed. 

There is a direct way to handle this now by adding the environment variables to the `project.json` file, for example:

```json
{
  "name": "goxample",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "projectType": "application",
  "sourceRoot": "apps/goxample",
  "tags": [],
  "targets": {
    "build": {
      "executor": "@nx-go/nx-go:build",
      "options": {
        "main": "{projectRoot}/main.go",
        "env": {
          "CGO_ENABLED": "0",
          "GOOS": "linux"
        }
      }
    },
    "serve": {
      "executor": "@nx-go/nx-go:serve",
      "options": {
        "main": "{projectRoot}/main.go"
      }
    },
    "test": {
      "executor": "@nx-go/nx-go:test"
    },
    "lint": {
      "executor": "@nx-go/nx-go:lint"
    },
    "tidy": {
      "executor": "@nx-go/nx-go:tidy"
    }
  }
}
```

**Comment by utarwyn** [comment]
> @abramsimon 
> This issue is stale and should be closed.
> 
> There is a direct way to handle this now by adding the environment variables to the `project.json` file, for example:

Thank you for the feedback! So you think we won't need these environment variables dynamically depending on the current runtime environment? Because in your example, they are static regardless of the operating system.

**Comment by abramsimon** [comment]
@utarwyn Thanks for the reply! You're correct that my example didn't really address the original issue as stated. Oops! I do believe that my point stands and that you shouldn't put any more effort into this particular issue. Let me elaborate...

My team is using nx-go in the same way that OP described: we use MacOS for development and deploy to a linux container environment.

For local development and testing we either:
* run the code via the nx `serve` target with no environment variables (the underlying `go run` command works without them)
* add a secondary nx target called `build-local` that has the correct env vars set, for example:
```
  "targets": {
    "build-local": {
      "executor": "@nx-go/nx-go:build",
      "options": {
        "main": "{projectRoot}/main.go",
        "env": {
          "CGO_ENABLED": "0",
          "GOOS": "darwin",
          "GOARCH": "arm64"
        }
      }
    },
  }
```

This allows the original `build` target to be used in CI. Or you could do the reverse and add a new target for CI and use the original for local development.

The point being that the nx-go plugin doesn't need to do anything special to support OP's use-case.

**Comment by utarwyn** [comment]
@abramsimon thank you for the detailed explanation! Much appreciated 👍 

In fact, several targets can be created to meet the initial need. So I'm closing this ticket, and if you have a bit of time it would be quite relevant to have [a discussion here](https://github.com/nx-go/nx-go/discussions/new?category=ideas) to explain how to do it.
