### ISSUE TITLE
File naming conventions

### ISSUE THREAD

**Issue by adlion** [nx-go/nx-go#79]
I have used your library for some of my projects and  have seen that naming conventions for go and angular are a bit different.

It would be great to have an option to choose to follow Go naming conventions for files.

Angular use `-` and Go is suggested to use `_`

If you think is a valid option I would be happy to work on it.

Thank you for all your hard work.

**Comment by utarwyn** [comment]
Hello!
Sorry I didn't reply sooner, the plugin should now use the “_” characters as recommended by Go.
If you still have a problem, feel free to re-open the ticket or create a new one. 👍
