### ISSUE TITLE
Performance issue nx graph

### ISSUE THREAD

**Issue by meDavidNS** [nx-go/nx-go#82]
The current graph plugin  is awesome to get a good insight into a Go workspace, but currently takes around 7 minutes to complete on our repository with 3K+ go files. It is executing `go list --json <file>` for every go file in the repository which even without nx, would take around 6 minutes to complete.

One possible optimalisation could be to use one `go list --json all` for the whole repository. This would only give dependency / import information on a package level (not per .go file), but the question is if this downside would have any significant impact.

Any thoughts @phillipCouto ?

**Comment by phillipCouto** [comment]
Hmm, when you run `go list --json all` on your repo how long does that take?

The reason we went with the `go list` per file is we can work with the change tracking of Nx and only check dependencies per file instead of checking all.

We may be able to come up with a hybrid solution.

**Comment by meDavidNS** [comment]
`go list --json all` takes around 0.8 seconds on our repository.

I made version of the plugin that uses the Go AST to lookup the imports, see https://github.com/nx-go/nx-go/pull/84

@phillipCouto Could you see if this also works for you?

**Comment by phillipCouto** [comment]
> `go list --json all` takes around 0.8 seconds on our repository.
> 
> I made version of the plugin that uses the Go AST to lookup the imports, see #84
> 
> @phillipCouto Could you see if this also works for you?

@meDavidNS I have reviewed your PR and provided some feedback. Please take a look so we can get this merged.
