### ISSUE TITLE
Can we maintain multiple go.mod with nx-go?

### ISSUE THREAD

**Issue by khoanguyen-yang** [nx-go/nx-go#85]
What if I want each app inside `apps` having its own `go.mod`? How to achieve this and what is the proper way to run `go mod download`, `go mod tidy` and `go get`?

Thanks in advanced

**Comment by phillipCouto** [comment]
When creating an app add the useGoWork flag which will setup a workspace file at the workspace root and mod files in each app.

**Comment by utarwyn** [comment]
Hello! This feature is enabled by default in nx-go from version 3 onwards. I invite you to try it out if you still need it!
You can also find more information [in the changelog here](https://github.com/nx-go/nx-go/releases/tag/v3.0.0-beta.0).
Regards
