### ISSUE TITLE
Update stats on the Nx Plugin Registry

### ISSUE THREAD

**Issue by isaacplmann** [nx-go/nx-go#91]
This plugin is missing the Nx version and Github Stars on the [Nx Plugin Registry](https://nx.dev/extending-nx/registry).  To fix this, you need to publish a new version of the plugin that includes:

(1) `@nx/devkit` as a `dependency` (or `peerDependency`) and
(2) a `repository.url` that points to this repo.  i.e.

```json
{
  "repository": {
    "type": "git",
    "url": "https://github.com/nrwl/nx.git",
    "directory": "packages/web"
  }
}
```

Thanks,
Isaac (Nx Team)

**Comment by utarwyn** [comment]
Hello @isaacplmann!
Thank you for the feedback. I have published **nx-go v3** with that addition. GitHub stars are now displayed correctly in the plugin card. But it doesn't seem to display the supported Nx versions... am I missing something?

Here is the updated `package.json`:
https://github.com/nx-go/nx-go/blob/6d447a2b8a6926be2730cb00ba3bb954ed650264/packages/nx-go/package.json#L12-L23

Screenshot:
![image](https://github.com/nx-go/nx-go/assets/9255967/7f90e25e-34b1-4535-80bd-753916e9009e)
